Avoid error when StatusMeta is None
/data/addons/plugin.video.vrt.nu/resources/lib/api.py", line 2757, in convert_episode
                                                       status = next((item.get('value') for item in episode.get('statusMeta', [])), None)
                                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                   TypeError: 'NoneType' object is not iterable